### PR TITLE
Use Go 1.7 in Drone and golang-version-check.

### PR DESCRIPTION
**Pull request by peggyl**
You were assigned as the most active recent contributor to this repo.
Please reassign and share the joy of Go 1.7 if needed, or ask in #golang
if you have any questions.

### CODE REVIEW

**Comment by mohit** [comment]
is it okay if I get to this in a couple of days?

**Comment by peggyl** [comment]
@mohit I fixed the build error in https://github.com/Clever/sphinx/pull/61/commits/1cb1a19244580c9d364979901e49356637c91d38 and the merge conflict with `.drone.yml` in a rebase. Can you take a look?

**Comment by peggyl** [comment]
Adding someone from Apps as a reviewer as well, since sphinx is actually owned by the Apps team.

**Comment by drhurd** [comment]
LGTM!

**Pull request merged**
